export let dogs = [
  {
    id: 0,
    name: "Maxine",
    avatar: "images/dog-rex.jpg",
    age: 25,
    bio:
      'Maneki-neko netsuke. Goat yoga. If you thought "Cats & Dogs" was funny, just click no and move along.',
    hasLiked: [],
    hasSwiped: [],
  },
  {
    id: 1,
    name: "Bella",
    avatar: "images/dog-bella.jpg",
    age: 43,
    bio: "Yup, yup, that's my owner! U can meet him if you want!! Yup, yup!",
    hasLiked: [],
    hasSwiped: [],
  },
  {
    id: 2,
    name: "Teddy",
    avatar: "images/dog-teddy.jpg",
    age: 30,
    bio: "How you doin?",
    hasLiked: [],
    hasSwiped: [],
  },
  {
    id: 3,
    name: "Robin",
    avatar: "images/husky.jpg",
    age: 22,
    bio: "A little shy, a little adventurous",
    hasLiked: [],
    hasSwiped: [],
  },
  {
    id: 4,
    name: "Frances",
    avatar: "images/perky-ears.jpg",
    age: 23,
    bio: "How about a sniff or two?",
    hasLiked: [],
    hasSwiped: [],
  },
  {
    id: 5,
    name: "Cooper",
    avatar: "images/golden.jpg",
    age: 24,
    bio: "I'm a lover not a fighter",
    hasLiked: [],
    hasSwiped: [],
  },
];
